//! Build script for mempool-ipc Phase 1.
//!
//! Reads MemPool hardware configuration from environment variables and
//! generates `config.rs` with compile-time constants matching the C
//! build's `-D` defines.

use std::env;
use std::fs;
use std::path::Path;

fn env_u32(name: &str, default: u32) -> u32 {
    env::var(name)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

fn main() {
    let num_cores = env_u32("NUM_CORES", 256);
    let num_groups = env_u32("NUM_GROUPS", 4);
    let cores_per_tile = env_u32("NUM_CORES_PER_TILE", 4);
    let banking_factor = env_u32("BANKING_FACTOR", 4);
    let stack_size = env_u32("STACK_SIZE", 2048);
    let seq_mem_size = env_u32("SEQ_MEM_SIZE", 2048);
    let xqueue_size = env_u32("XQUEUE_SIZE", 64);

    // Generate config.rs with platform constants
    let out_dir = env::var("OUT_DIR").unwrap();
    let config_path = Path::new(&out_dir).join("config.rs");
    fs::write(
        &config_path,
        format!(
            "// Auto-generated by build.rs — do not edit.\n\
             pub const NUM_CORES: u32 = {num_cores};\n\
             pub const NUM_GROUPS: u32 = {num_groups};\n\
             pub const NUM_CORES_PER_TILE: u32 = {cores_per_tile};\n\
             pub const BANKING_FACTOR: u32 = {banking_factor};\n\
             pub const STACK_SIZE: u32 = {stack_size};\n\
             pub const SEQ_MEM_SIZE: u32 = {seq_mem_size};\n\
             pub const XQUEUE_SIZE: u32 = {xqueue_size};\n\
             pub const NUM_BANKS_PER_TILE: u32 = {cores_per_tile} * {banking_factor};\n"
        ),
    )
    .expect("failed to write config.rs");

    for var in &[
        "NUM_CORES",
        "NUM_GROUPS",
        "NUM_CORES_PER_TILE",
        "BANKING_FACTOR",
        "STACK_SIZE",
        "SEQ_MEM_SIZE",
        "XQUEUE_SIZE",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }

}
